[package]
name = "test-deno-bindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "test_deno_bindgen"
crate-type = ["cdylib"]

[dependencies]
deno_bindgen = "0.5.1"
